config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'lists#index'

  resources :lists do
    member do
      get :favorite
      get :show_stream
    end

    collection do
      get :stream
      get :favorites
    end
  end

  resources :cards, only: [:show, :update, :destroy] do
    member do
      get :close
      get :show_stream
    end
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  has_many :checklists, dependent: :destroy do
    def progress
      "#{ resolved.length } / #{ length }"
    end
  end
  belongs_to :list

  default_scope -> { order('CASE WHEN closed_at IS NOT NULL then 0 else 1 END DESC, created_at DESC') }

  validates_presence_of :name, :description
  validates_uniqueness_of :name, scope: :list_id, on: :create

  accepts_nested_attributes_for :checklists, allow_destroy: true

  after_save :set_closed_at

  def close
    checklists.each do |checklist|
      checklist.update_attributes(resolved: true)
    end

    set_closed_at
  end

  def closed?
    closed_at.present?
  end

  protected
  def set_closed_at
    return if checklists.length == 0

    time = if checklists.resolved.length == checklists.length
       Time.now
    else
      nil
    end

    update_columns(closed_at: time, updated_at: Time.now)
  end
end

app/models/checklist.rb
class Checklist < ActiveRecord::Base
  belongs_to :card

  scope :resolved, -> { where('resolved=? ', true) }

  validates_presence_of :description, :card
end

app/models/favorite_list.rb
class FavoriteList < ActiveRecord::Base
  belongs_to :list
  belongs_to :user

  validates_presence_of :list, :user

  scope :by_list, -> (list) { where(list: list) }
  scope :by_user, -> (user) { where(user: user) }
end

app/models/list.rb
class List < ActiveRecord::Base
  has_many :cards, dependent: :destroy
  has_many :favorite_lists, dependent: :destroy
  belongs_to :user

  validates_presence_of :name, :user
  validates_uniqueness_of :name, scope: :user_id
  validates :only_me, inclusion: { in: [true, false] }

  scope :publics, -> (user) { where('only_me=? OR user_id=?', false, user).priority(user) }
  scope :priority, -> (user) { order("CASE WHEN user_id = #{ user.id } then 1 else 0 END DESC, updated_at DESC") }
  scope :favorites, -> (user) { joins(:favorite_lists).where('favorite_lists.user_id = ?', user) }

  accepts_nested_attributes_for :cards, allow_destroy: true

  def has_favorited?(user)
    favorite_lists.by_user(user).present?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :favorite_lists, dependent: :destroy
  has_many :lists, dependent: :destroy

  def gravatar
    "http://www.gravatar.com/avatar/#{ Digest::MD5.hexdigest(email) }"
  end

  def find_favorite_list(list)
    favorite_lists.by_list(list)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  private
  def build_stream(dates, path)
    response.headers['Content-Type'] = "text/event-stream\n\n"

    begin
      response.stream.write "id: #{ rand(0..999999) }\n"
      response.stream.write "retry: 10000\n"
      response.stream.write "event: updates\n"
      response.stream.write "data: #{ JSON.dump({ dates: dates, path: path }) }\n\n"
    rescue IOError
      p IOError
    ensure
      response.stream.close
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :can_handler!, only: [:update, :destroy, :close]

  def show
    @card = CardPresenter.new Card.find params[:id]
  end

  def update
    @card = CardPresenter.new Card.find params[:id]

    if @card.get_subject.update_attributes permit_params
      redirect_to card_path(@card.get_subject)
    else
      render action: :show
    end
  end

  def destroy
    card = Card.find params[:id]

    if card.destroy
      redirect_to list_path(card.list)
    else
      render action: :show
    end
  end

  def close
    card = Card.find params[:id]

    if card.close
      redirect_to card_path(card)
    else
      render action: :show
    end
  end

  def show_stream
    dates = Card.find(params[:id]).updated_at.strftime('%d/%m/%Y %I:%M:%S')
    build_stream([dates], card_path(params[:id]))
  end

  private
  def permit_params
    params.require(:card).permit(:name, :description, :updated_at, :checklists_attributes => [:resolved, :description, :id, :_destroy])
  end

  def can_handler!
    card = Card.find(params[:id])

    if current_user != card.list.user
      redirect_to card_path(card), alert: "You don't own this record"
    end
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :can_handler!, only: [:edit, :update, :destroy]

  def index
    @lists = ListsPresenter.new List.publics(current_user)
  end

  def show
    @list = ListPresenter.new List.find(params[:id])
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new permit_params

    if @list.save
      redirect_to list_path(@list)
    else
      render action: :new
    end
  end

  def edit
    @list = List.find params[:id]
  end

  def update
    @list = List.find params[:id]

    if @list.update_attributes permit_params
      redirect_to list_path(@list)
    else
      render action: :edit
    end
  end

  def destroy
    @list = List.find(params[:id])

    if @list.destroy
      redirect_to lists_path
    else
      render action: :edit
    end
  end

  def favorite
    list = List.find(params[:id])
    favorite = current_user.find_favorite_list(list)

    if favorite.present?
      favorite.first.destroy
    else
      current_user.favorite_lists.new(list_id: params[:id]).save
    end

    redirect_to lists_path
  end

  def favorites
    @lists = ListsPresenter.new(List.favorites(current_user))
  end

  def stream
    dates = List.favorites(current_user).map do |list|
      list.updated_at.strftime('%d/%m/%Y %I:%M:%S')
    end

    build_stream(dates, lists_path)
  end

  def show_stream
    dates = List.find(params[:id]).updated_at.strftime('%d/%m/%Y %I:%M:%S')
    build_stream([dates], list_path(params[:id]))
  end

  private
  def permit_params
    params.require(:list).permit(:only_me, :name, :cards_attributes => [:name, :description, :id, :_destroy])
  end

  def can_handler!
    list = List.find(params[:id])

    if current_user != list.user
      redirect_to list_path(list), alert: "You don't own this record"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def checked_class_name(checklist)
    checklist.resolved ? 'checked' : ''
  end

  def disabled_class_name(card)
    card.closed_at ? 'disabled' : ''
  end

  def errors_wrapper(record)
    if record.errors.present?
      content_tag :div, class: 'alert alert-warning padding-10 margin-tb-10' do
        content_tag :ul, class: 'padding-rl-20' do
          record.errors.full_messages.map do |message|
            content_tag(:li) { message }
          end.join('').html_safe
        end
      end
    end
  end

  def notices_wrapper
    if notice
      content_tag :div, class: 'alert alert-info' do
        content_tag(:p, class: 'notice') { notice }
      end
    end
  end

  def alerts_wrapper
    if alert
      content_tag :div, class: 'alert alert-warning' do
        content_tag(:p, class: 'alert') { alert }
      end
    end
  end

  def nav_partial
    user_signed_in? ? 'shared/menu_logged' : 'shared/menu_unlogged'
  end
end

app/helpers/cards_helper.rb
module CardsHelper
  def setup_card(card)
    card.tap do |r|
      r.checklists.build if r.checklists.blank?
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
  def setup_list(list)
    list.tap do |r|
      r.cards.build if r.cards.blank?
    end
  end

  def is_my(list)
    list.user == current_user ? 'is_my' : ''
  end
end

app/views/cards/_checklist.html.erb
<%= c.check_box :resolved %>

<span name='resolved' class="<%= checked_class_name(c.object) %>">
  <%= c.object.description %>
</span>

app/views/cards/_checklists.html.erb
<ul class='list-group'>
  <li class='list-group-item active'><h4>Checklist</h4></li>
  <div class='items'>
    <%= f.nested_fields_for :checklists do |c| %>
      <li class='list-group-item'>

        <fieldset class="item">
          <div class='nested-inputs pull-left margin-tb-10'>
            <%= render partial: @card.checklist_partial(c.object), locals: { c: c } %>
            <%= c.hidden_field :id %>
            <%= c.hidden_field :_destroy %>
          </div>

          <a href="#" class="remove btn btn-danger btn-xs margin-tb-10">remove</a>

        </fieldset>
      </li>
    <% end %>
  </div>

  <div class='actions margin-tb-10'>
    <a href="#" class="add btn btn-info btn-xs">add checklist</a>
  </div>
</ul>

<% content_for :javascript do %>
  <script>
    $(document).ready(function(e) {
      $('form').nestedFields();
    });
  </script>
<% end %>

app/views/cards/_new_checklist.html.erb
<%= c.label :resolved %>
<%= c.check_box :resolved %>
<%= c.text_field :description, placeholder: 'description', class: 'form-control' %>

app/views/cards/show.html.erb
<section>
  <%= form_for setup_card(@card.get_subject), html: { multipart: true, class: 'center-block' } do |f| %>
    <%= errors_wrapper(@card.get_subject) %>

    <div class='clearfix'>
      <h2 class='pull-left'>
        <%= @card.name %>
      </h2>

      <%= @card.closed_label %>
    </div>

    <p>
      <%= @card.description %>
      <%= f.hidden_field :updated_at, value: Time.now %>
    </p>

    <div id='checklists' class='padding-tb-10'>
      <%= render partial: 'cards/checklists', locals: { f: f } %>
    </div>

    <div class='actions'>
      <%= f.submit 'save', class: 'btn btn-success' %>
      <%= link_to 'close', close_card_path(@card.id), class: 'btn btn-info' %>
      <%= link_to 'delete', card_path(@card.id), method: :delete, class: 'btn btn-danger' %>
      <%= link_to 'back', list_path(@card.list), class: 'btn btn-default' %>
    </div>
  <% end %>
</section>

<%= content_for :javascript do %>
  <script type="text/javascript">
    var dates = ["<%= @card.updated_at.strftime('%d/%m/%Y %I:%M:%S') %>"];
    new Event(dates, "/cards/<%= @card.id %>/show_stream")
  </script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Todo list</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' unless controller_name == 'sessions' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'shared/nav' %>

    <main id='content' class='jumbotron padding-20'>
      <%= notices_wrapper %>
      <%= alerts_wrapper %>

      <%= yield %>
    </main>
  </body>
  <%= yield :javascript %>
</html>

app/views/lists/_card_form.html.erb
<h3>Cards</h3>
<div class='items'>
  <%= f.nested_fields_for :cards do |c| %>
    <fieldset class="item">
      <div class='nested-inputs pull-left margin-r-10 margin-tb-10'>
        <%= c.text_field :name, placeholder: 'card name', class: 'form-control' %>
        <%= c.text_area :description, placeholder: 'card description', class: 'form-control' %>
        <%= c.hidden_field :id %>
        <%= c.hidden_field :_destroy %>
      </div>

      <a href="#" class="remove btn btn-danger btn-xs margin-tb-20">remove</a>

    </fieldset>
  <% end %>
</div>

<div class='action margin-tb-10'>
  <a href="#" class="add btn btn-info btn-xs">add card</a>
</div>

<% content_for :javascript do %>
  <script>
    $(document).ready(function(e) {
      $('form').nestedFields();
    });
  </script>
<% end %>

app/views/lists/_cards_list.html.erb
<ul>
  <%- @list.cards.each do |card| %>
    <li class="list-group-item <%= disabled_class_name(card) %>">
      <%= link_to card_path(card) do %>
        <%= card.name %>

        <span class='badge pull-right margin-tb-5'>
          <%= card.checklists.progress %>
        </span>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/lists/_form.html.erb
<%= form_for setup_list(@list), html: { multipart: true, class: 'center-block' } do |f| %>
  <%= errors_wrapper(@list) %>

  <%= f.label :only_me %>
  <%= f.check_box :only_me %>

  <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>

  <%= render partial: 'lists/card_form', locals: { f: f } %>

  <%= f.submit 'save', class: 'btn btn-success' %>
<% end %>

app/views/lists/_list.html.erb
<div class='row'>
  <%- @lists.get_subject.each do |list| %>
    <section class='col-xs-12 col-sm-6 col-md-4'>
      <div class='panel panel-default'>
        <div class="panel-heading clearfix <%= is_my(list) %>">
          <%= link_to list_path(list) do %>
            <h2 class='pull-left'>
              <small><%= list.name %></small>
            </h2>

            <%= image_tag list.user.gravatar, class: 'img-circle margin-rl-10 pull-left', size: '25x25' %>

            <span class='badge pull-right margin-tb-5'>
              <%= list.cards.length %>
            </span>
          <% end %>
        </div>

        <div class='panel-body'>
          <%= @lists.favorite_button(current_user, list) %>
        </div>
      </div>
    </section>
  <% end %>
</div>

<%= content_for :javascript do %>
  <script type="text/javascript">
    var dates = <%= raw @lists.updates_favorite_lists(current_user) %>;
    new Event(dates, '/lists/stream')
  </script>
<% end %>

app/views/lists/edit.html.erb
<h2>Edit list: <%= @list.name %></h2>

<%= render 'lists/form' %>

<div class='external-buttons padding-tb-10'>
  <%= link_to 'delete', list_path(@list), method: :delete, class: 'btn btn-danger' %>
</div>

app/views/lists/favorites.html.erb
<h2>My favorites lists</h2>

<div id='list' class='padding-tb-10'>
  <%= render @lists.list_partial %>
</div>

app/views/lists/index.html.erb
<%= link_to 'new list', new_list_path, class: 'btn btn-primary' %>

<div id='list' class='padding-tb-10'>
  <%= render @lists.list_partial %>
</div>

app/views/lists/new.html.erb
<h2>New list</h2>

<%= render 'lists/form' %>

app/views/lists/show.html.erb
<div id='cards' class='padding-tb-10'>
  <section class='list-group'>
    <div class='list-group-item active clearfix'>
      <h4 class='pull-left'>
        <%= @list.name %>
      </h4>

      <%= @list.edit_button(current_user) %>
    </div>
    <%= render @list.card_partial %>
  </section>
</div>

<%= link_to 'back', lists_path, class: 'btn btn-primary' %>

<%= content_for :javascript do %>
  <script type="text/javascript">
    var dates = ["<%= @list.updated_at.strftime('%d/%m/%Y %I:%M:%S') %>"];
    new Event(dates, "/lists/<%= @list.id %>/show_stream")
  </script>
<% end %>

app/views/shared/_menu_logged.html.erb
<ul class='nav nav-pills pull-right'>
  <li class='margin-tb-10'>
    <a class='reload hidden label label-success margin-tb-5'>
      refresh
    </a>
  </li>

  <li class='margin-tb-10'>
    <%= link_to edit_user_registration_path do %>
      <%= image_tag current_user.gravatar, class: 'img-circle', size: '25x25' %>
    <% end %>
  </li>

  <li class='margin-tb-10'>
    <%= link_to 'lists', lists_path, class: 'text-muted' %>
  </li>

  <li class='margin-tb-10'>
    <%= link_to 'favorites', favorites_lists_path, class: 'text-muted' %>
  </li>

  <li class='margin-tb-10'>
    <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: 'text-muted' %>
  </li>
</ul>

app/views/shared/_menu_unlogged.html.erb
<ul class='nav nav-pills pull-right'>
  <li class='margin-tb-10'>
    <%= link_to 'login', new_user_session_path, class: 'text-muted' %>
  </li>

  <li class='margin-tb-10'>
    <%= link_to 'sign up', new_user_registration_path, class: 'text-muted' %>
  </li>
</ul>

app/views/shared/_nav.html.erb
<nav class='navbar navbar-default navbar-inverse padding-rl-20'>
  <div class='navbar-header pull-left'>
    <%= link_to root_path do %>
      <h1>
        <small>Todo List</small>
      </h1>
    <% end %>
  </div>

  <%= render nav_partial %>
</nav>

app/views/shared/_warning.html.erb
<div class='alert alert-warning'>There is nothing registered</div>